"use client";

import { useEffect, useState } from "react";
import { ImagePlus, LogIn, Upload, X } from "lucide-react";
import SiteHeader from "../../components/site-header";
import SiteFooter from "../../components/site-footer";
import PropertyLocation from "../../components/property-location";
import { supabase } from "../../lib/supabase";

const input="w-full rounded-xl border border-[#d7e3e8] bg-white px-4 py-3 text-sm text-[#102638] outline-none focus:border-[#0bb89b] focus:ring-2 focus:ring-[#0bb89b]/10";
const label="mb-2 block text-xs font-bold uppercase tracking-[1.3px] text-[#547083]";
type F={purpose:string;category:string;property_type:string;title:string;description:string;price:string;rent_monthly:string;bedrooms:string;bathrooms:string;area_sqft:string;plot_area_sqyd:string;furnishing:string;possession:string;parking_spaces:string;address_line:string;city:string;locality:string;pincode:string;latitude:number|null;longitude:number|null;place_id:string|null};
const initial:F={purpose:"sale",category:"residential",property_type:"Apartment",title:"",description:"",price:"",rent_monthly:"",bedrooms:"",bathrooms:"",area_sqft:"",plot_area_sqyd:"",furnishing:"",possession:"ready_to_move",parking_spaces:"",address_line:"",city:"",locality:"",pincode:"",latitude:null,longitude:null,place_id:null};
type Preview={file:File;url:string};

export default function PostPropertyPage(){
 const[form,setForm]=useState(initial);const[user,setUser]=useState<any>(null);const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[mode,setMode]=useState<"signup"|"login">("signup");const[files,setFiles]=useState<Preview[]>([]);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");
 useEffect(()=>{if(!supabase)return;supabase.auth.getUser().then(({data})=>setUser(data.user));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{const q=new URLSearchParams(window.location.search);if(q.get("mode")==="login")setMode("login")},[]);
 const set=(k:keyof F,v:any)=>setForm(x=>({...x,[k]:v}));
 const ensure=async(id:string)=>{if(!supabase)return;const r=await supabase.from("profiles").upsert({id,role:"owner",email:user?.email||null},{onConflict:"id",ignoreDuplicates:true});if(r.error)throw r.error};
 const authenticate=async()=>{if(!supabase)return;setSaving(true);setError("");setMessage("");try{const r=mode==="login"?await supabase.auth.signInWithPassword({email:email.trim(),password}):await supabase.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:`${window.location.origin}/auth/confirm`}});if(r.error)throw r.error;if(r.data.session&&r.data.user){await ensure(r.data.user.id);setUser(r.data.user);setMessage(mode==="login"?"Signed in successfully.":"Account created successfully. You can now submit your property.")}else setMessage("Account created. Please confirm your email using the link we sent you. After confirmation, you can return to UNLIVO and submit your property.")}catch(e:any){setError(e?.message||"We could not complete your request.")}finally{setSaving(false)}};
 const choose=(incoming:FileList|null)=>{if(!incoming)return;const selected=Array.from(incoming).filter(f=>f.type.startsWith("image/"));const all=[...files.map(x=>x.file),...selected];const unique=all.filter((f,i,a)=>a.findIndex(x=>x.name===f.name&&x.size===f.size&&x.lastModified===f.lastModified)===i).slice(0,10);setFiles(unique.map(f=>({file:f,url:URL.createObjectURL(f)})))};
 const remove=(i:number)=>setFiles(a=>{URL.revokeObjectURL(a[i].url);return a.filter((_,n)=>n!==i)});
 const save=async(status:"draft"|"pending_review")=>{if(!supabase||!user){setError("Please create an account or sign in first.");return}if(!form.title.trim()||!form.property_type.trim()||!form.city.trim()||!form.locality.trim()){setError("Please complete the title, property type, city and locality.");return}if(form.purpose==="sale"&&!form.price){setError("Please enter the sale price.");return}if(form.purpose==="rent"&&!form.rent_monthly){setError("Please enter the monthly rent.");return}setSaving(true);setError("");setMessage("");try{await ensure(user.id);const payload:any={listed_by:user.id,owner_id:user.id,purpose:form.purpose,category:form.category,property_type:form.property_type,title:form.title.trim(),description:form.description.trim()||null,price:form.purpose==="sale"?Number(form.price)||null:null,rent_monthly:form.purpose==="rent"?Number(form.rent_monthly)||null:null,bedrooms:form.bedrooms?Number(form.bedrooms):null,bathrooms:form.bathrooms?Number(form.bathrooms):null,area_sqft:form.area_sqft?Number(form.area_sqft):null,plot_area_sqyd:form.plot_area_sqyd?Number(form.plot_area_sqyd):null,furnishing:form.furnishing||null,possession:form.possession||null,parking_spaces:form.parking_spaces?Number(form.parking_spaces):null,address_line:form.address_line||null,city:form.city,locality:form.locality,pincode:form.pincode||null,latitude:form.latitude,longitude:form.longitude,place_id:form.place_id,status};const r=await supabase.from("properties").insert(payload).select("id").single();if(r.error)throw r.error;const propertyId=r.data.id;if(status==="pending_review"){const rr=await supabase.from("property_reviews").insert({property_id:propertyId,decision:"pending"});if(rr.error)throw rr.error}for(let i=0;i<files.length;i++){const f=files[i].file;const ext=f.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${user.id}/${propertyId}/${crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from("property-media").upload(path,f,{cacheControl:"3600",upsert:false});if(up.error)throw up.error;const m=await supabase.from("property_media").insert({property_id:propertyId,storage_path:path,media_type:"image",sort_order:i,is_cover:i===0});if(m.error)throw m.error}if(status==="pending_review"){window.location.assign(`/post-property/confirmation?id=${propertyId}`);return}setMessage("Draft saved successfully.");setForm(initial);files.forEach(f=>URL.revokeObjectURL(f.url));setFiles([])}catch(e:any){setError(e?.message||"We could not save the property.")}finally{setSaving(false)}};
 return <main className="min-h-screen bg-[#f7fafb] text-[#102638]"><SiteHeader/><section className="container max-w-5xl py-10 lg:py-14"><div className="max-w-2xl"><p className="text-[11px] font-bold uppercase tracking-[3px] text-[#547083]">List with UNLIVO</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-1.5px]">Post a Property</h1><p className="mt-3 text-sm leading-6 text-[#687987]">Add your property once, keep control of your listing, and reach buyers and tenants searching on UNLIVO.</p></div>{message&&<div className="mt-7 rounded-xl border border-[#bfe9df] bg-[#effbf8] px-4 py-3 text-sm font-semibold text-[#087f73]">{message}</div>}{error&&<div className="mt-7 rounded-xl border border-[#efd0d0] bg-[#fff7f7] px-4 py-3 text-sm font-semibold text-[#8b4b4b]">{error}</div>}
 {!user?<div className="mt-8 rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm lg:p-8"><div className="flex items-start gap-4"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-[#e9faf6] text-[#0b8f79]"><LogIn size={20}/></div><div><h2 className="text-xl font-extrabold">{mode==="signup"?"Create an account to list":"Sign in to list your property"}</h2><p className="mt-1 text-sm text-[#687987]">Your account keeps your listings, photos and enquiries connected.</p></div></div><div className="mt-6 grid gap-4 md:grid-cols-2"><div><label className={label}>Email</label><input className={input} type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></div><div><label className={label}>Password</label><input className={input} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/></div></div><button onClick={authenticate} disabled={saving||!email||!password} className="mt-5 cursor-pointer rounded-xl bg-[#123b53] px-6 py-3 text-sm font-bold text-white disabled:opacity-50">{saving?"Please wait…":mode==="signup"?"Create Account":"Sign In"}</button><button onClick={()=>{setMode(mode==="signup"?"login":"signup");setError("");setMessage("")}} className="ml-4 cursor-pointer text-sm font-bold text-[#087f73]">{mode==="signup"?"Already have an account? Sign in":"Need an account? Sign up"}</button></div>:<form onSubmit={e=>{e.preventDefault();save("pending_review")}} className="mt-8 space-y-6"><div className="rounded-3xl border border-[#cfe9e4] bg-[#f1fbf8] p-5"><p className="text-sm font-extrabold text-[#087f73]">Your listing will be reviewed before it goes live.</p><p className="mt-1 text-sm leading-6 text-[#547083]">After you submit it, UNLIVO will place it in review. You’ll get a confirmation page with the listing link and its current status.</p></div>
 <div className="rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm lg:p-8"><h2 className="text-xl font-extrabold">1. Listing basics</h2><div className="mt-6 grid gap-4 md:grid-cols-2"><div><label className={label}>Purpose</label><div className="grid grid-cols-2 gap-2">{[["sale","For Sale"],["rent","For Rent"]].map(([v,t])=><button type="button" key={v} onClick={()=>set("purpose",v)} className={`cursor-pointer rounded-xl border px-4 py-3 text-sm font-bold ${form.purpose===v?"border-[#0bb89b] bg-[#e9faf6] text-[#087f73]":"border-[#d7e3e8]"}`}>{t}</button>)}</div></div><div><label className={label}>Category</label><select className={input} value={form.category} onChange={e=>set("category",e.target.value)}><option value="residential">Residential</option><option value="commercial">Commercial</option><option value="plot_land">Plots & Land</option><option value="project">Projects</option></select></div><div><label className={label}>Property type</label><input className={input} value={form.property_type} onChange={e=>set("property_type",e.target.value)} placeholder="Apartment, Villa, Office, Plot…"/></div><div><label className={label}>{form.purpose==="sale"?"Sale price (₹)":"Monthly rent (₹)"}</label><input className={input} type="number" min="0" value={form.purpose==="sale"?form.price:form.rent_monthly} onChange={e=>set(form.purpose==="sale"?"price":"rent_monthly",e.target.value)}/></div><div className="md:col-span-2"><label className={label}>Listing title</label><input className={input} value={form.title} onChange={e=>set("title",e.target.value)} placeholder="3 BHK Premium Apartment in Sector 88"/></div><div className="md:col-span-2"><label className={label}>Description</label><textarea className={`${input} min-h-32`} value={form.description} onChange={e=>set("description",e.target.value)} placeholder="Describe the property, condition, highlights and anything a buyer should know…"/></div></div></div>
 <div className="rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm lg:p-8"><h2 className="text-xl font-extrabold">2. Property details</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{form.category==="residential"&&<><div><label className={label}>Bedrooms</label><input className={input} type="number" min="0" value={form.bedrooms} onChange={e=>set("bedrooms",e.target.value)}/></div><div><label className={label}>Bathrooms</label><input className={input} type="number" min="0" value={form.bathrooms} onChange={e=>set("bathrooms",e.target.value)}/></div></>}{form.category!=="plot_land"?<div><label className={label}>Area (sq ft)</label><input className={input} type="number" min="0" value={form.area_sqft} onChange={e=>set("area_sqft",e.target.value)}/></div>:<div><label className={label}>Plot area (sq yd)</label><input className={input} type="number" min="0" value={form.plot_area_sqyd} onChange={e=>set("plot_area_sqyd",e.target.value)}/></div>}<div><label className={label}>Parking spaces</label><input className={input} type="number" min="0" value={form.parking_spaces} onChange={e=>set("parking_spaces",e.target.value)}/></div><div><label className={label}>Furnishing</label><select className={input} value={form.furnishing} onChange={e=>set("furnishing",e.target.value)}><option value="">Select</option><option value="unfurnished">Unfurnished</option><option value="semi_furnished">Semi furnished</option><option value="fully_furnished">Fully furnished</option></select></div><div><label className={label}>Possession</label><select className={input} value={form.possession} onChange={e=>set("possession",e.target.value)}><option value="ready_to_move">Ready to move</option><option value="under_construction">Under construction</option><option value="pre_launch">Pre-launch</option><option value="resale">Resale</option></select></div></div></div>
 <div className="rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm lg:p-8"><h2 className="text-xl font-extrabold">3. Location</h2><div className="mt-6"><label className={label}>Property address</label><PropertyLocation value={form.address_line} onChange={v=>set("address_line",v)} onPlace={p=>setForm(x=>({...x,address_line:p.address,city:p.city,locality:p.locality,pincode:p.pincode,latitude:p.latitude,longitude:p.longitude,place_id:p.placeId}))}/></div><div className="mt-5 grid gap-4 md:grid-cols-3"><div><label className={label}>City</label><input className={input} value={form.city} onChange={e=>set("city",e.target.value)} placeholder="Mohali"/></div><div><label className={label}>Locality / Sector</label><input className={input} value={form.locality} onChange={e=>set("locality",e.target.value)} placeholder="Sector 88"/></div><div><label className={label}>Pincode</label><input className={input} value={form.pincode} onChange={e=>set("pincode",e.target.value)} placeholder="140301"/></div></div></div>
 <div className="rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm lg:p-8"><div className="flex items-center justify-between"><div><h2 className="text-xl font-extrabold">4. Photos</h2><p className="mt-1 text-sm text-[#687987]">Add up to 10 photos. The first photo will be the cover.</p></div><ImagePlus size={22} className="text-[#0b8f79]"/></div><label className="mt-6 flex cursor-pointer items-center justify-center rounded-2xl border-2 border-dashed border-[#cbdde3] bg-[#f8fbfc] px-6 py-10 text-center hover:border-[#0bb89b]"><input type="file" accept="image/*" multiple className="hidden" onChange={e=>choose(e.target.files)}/><span><Upload className="mx-auto" size={24}/><span className="mt-2 block text-sm font-bold">Choose property photos</span><span className="mt-1 block text-xs text-[#687987]">JPG, PNG or WebP · up to 10 photos</span></span></label>{files.length>0&&<div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{files.map((f,i)=><div key={f.url} className="relative overflow-hidden rounded-xl border border-[#dfe9ed]"><img src={f.url} alt={`Property photo ${i+1}`} className="aspect-square w-full object-cover"/><span className="absolute left-2 top-2 rounded bg-white/90 px-2 py-1 text-[10px] font-bold">{i===0?"Cover":`Photo ${i+1}`}</span><button type="button" onClick={()=>remove(i)} className="absolute right-2 top-2 flex h-7 w-7 cursor-pointer items-center justify-center rounded-full bg-white/90"><X size={14}/></button></div>)}</div>}</div>
 <div className="flex flex-wrap items-center justify-between gap-3"><p className="max-w-2xl text-xs leading-5 text-[#687987]">By submitting, you confirm that the information and photos are accurate. Your listing will be reviewed before it becomes public.</p><div className="flex shrink-0 gap-3"><button type="button" disabled={saving} onClick={()=>save("draft")} className="inline-flex h-12 min-w-[132px] cursor-pointer items-center justify-center rounded-xl border border-[#cbdde3] bg-white px-5 text-sm font-bold">Save Draft</button><button type="submit" disabled={saving} className="inline-flex h-12 min-w-[170px] cursor-pointer items-center justify-center rounded-xl bg-[#0bb89b] px-6 text-sm font-extrabold text-white hover:bg-[#087f73] disabled:cursor-wait disabled:opacity-70"><span className="w-[110px] text-center">{saving?"Submitting…":"Submit for Review"}</span></button></div></div></form>}</section><SiteFooter/></main>;
}