"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, ImagePlus, LogIn, Upload, X } from "lucide-react";
import { supabase } from "../../lib/supabase";

const inputClass = "w-full rounded-xl border border-[#d7e3e8] bg-white px-4 py-3 text-sm text-[#102638] outline-none transition focus:border-[#0bb89b] focus:ring-2 focus:ring-[#0bb89b]/10";
const labelClass = "mb-2 block text-xs font-bold uppercase tracking-[1.3px] text-[#547083]";

type FormState = { purpose:"sale"|"rent"; category:"residential"|"commercial"|"plot_land"|"project"; property_type:string; title:string; description:string; price:string; rent_monthly:string; bedrooms:string; bathrooms:string; area_sqft:string; plot_area_sqyd:string; furnishing:""|"unfurnished"|"semi_furnished"|"fully_furnished"; possession:""|"ready_to_move"|"under_construction"|"pre_launch"|"resale"; parking_spaces:string; address_line:string; city:string; locality:string; pincode:string };
const initialForm:FormState={purpose:"sale",category:"residential",property_type:"Apartment",title:"",description:"",price:"",rent_monthly:"",bedrooms:"",bathrooms:"",area_sqft:"",plot_area_sqyd:"",furnishing:"",possession:"ready_to_move",parking_spaces:"",address_line:"",city:"",locality:"",pincode:""};

type Preview = { file:File; url:string };

export default function PostPropertyPage(){
  const [form,setForm]=useState<FormState>(initialForm); const [user,setUser]=useState<any>(null); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [authMode,setAuthMode]=useState<"signup"|"login">("signup"); const [files,setFiles]=useState<Preview[]>([]); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");

  useEffect(()=>{ if(!supabase)return; supabase.auth.getUser().then(({data})=>setUser(data.user)); const {data}=supabase.auth.onAuthStateChange((_event,session)=>setUser(session?.user??null)); return()=>data.subscription.unsubscribe(); },[]);
  useEffect(()=>{ const params=new URLSearchParams(window.location.search); if(params.get("confirmed")==="1") setMessage("Email confirmed successfully. Your account is ready — you can now publish your property."); },[]);
  const set=(key:keyof FormState,value:string)=>setForm(c=>({...c,[key]:value} as FormState));
  const needsBedrooms=form.category==="residential" && form.property_type.toLowerCase()!=="plot";
  const needsArea=form.category!=="plot_land";

  const ensureProfile=async(id:string)=>{ if(!supabase)return; const result=await supabase.from("profiles").upsert({id,role:"buyer"},{onConflict:"id",ignoreDuplicates:true}); if(result.error)throw result.error; };

  const authenticate=async()=>{ if(!supabase)return setError("Supabase is not configured."); setError("");setMessage("");setSaving(true); try{ const redirectTo=`${window.location.origin}/auth/callback`; const result=authMode==="login" ? await supabase.auth.signInWithPassword({email:email.trim(),password}) : await supabase.auth.signUp({email:email.trim(),password},{options:{emailRedirectTo:redirectTo}}); if(result.error)throw result.error; if(result.data.session&&result.data.user){await ensureProfile(result.data.user.id);setUser(result.data.user);setMessage(authMode==="signup"?"Account created successfully. You can now publish your property.":"Signed in successfully.");} else {setMessage("Account created. Please confirm your email using the link we sent you. After confirmation, you will be returned to UNLIVO automatically.");} }catch(e:any){setError(e?.message||"We could not complete your account request.");}finally{setSaving(false);} };

  const chooseFiles=(incoming:FileList|null)=>{ if(!incoming)return; setError(""); const selected=Array.from(incoming).filter(f=>f.type.startsWith("image/")); const combined=[...files.map(x=>x.file),...selected]; const unique=combined.filter((f,i,a)=>a.findIndex(x=>x.name===f.name&&x.size===f.size&&x.lastModified===f.lastModified)===i).slice(0,10); setFiles(unique.map(file=>({file,url:URL.createObjectURL(file)}))); };
  const removeFile=(index:number)=>{setFiles(current=>{URL.revokeObjectURL(current[index].url);return current.filter((_,i)=>i!==index);});};

  const uploadImages=async(propertyId:string,userId:string)=>{ if(!supabase)return; for(let i=0;i<files.length;i++){const file=files[i].file;const extension=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${userId}/${propertyId}/${crypto.randomUUID()}.${extension}`;const uploaded=await supabase.storage.from("property-media").upload(path,file,{cacheControl:"3600",upsert:false});if(uploaded.error)throw uploaded.error;const media=await supabase.from("property_media").insert({property_id:propertyId,storage_path:path,media_type:"image",sort_order:i,is_cover:i===0});if(media.error)throw media.error;}};

  const submit=async(status:"draft"|"published")=>{ if(!supabase)return setError("Supabase is not configured in this deployment."); if(!user)return setError("Please create an account or sign in before saving your property."); if(!form.title.trim()||!form.city.trim()||!form.locality.trim()||!form.property_type.trim())return setError("Please complete the property title, type, city and locality."); if(form.purpose==="sale"&&!form.price)return setError("Please enter the sale price."); if(form.purpose==="rent"&&!form.rent_monthly)return setError("Please enter the monthly rent."); setSaving(true);setError("");setMessage(""); try{await ensureProfile(user.id);const payload:any={listed_by:user.id,owner_id:user.id,purpose:form.purpose,category:form.category,property_type:form.property_type.trim(),title:form.title.trim(),description:form.description.trim()||null,price:form.purpose==="sale"?Number(form.price)||null:null,rent_monthly:form.purpose==="rent"?Number(form.rent_monthly)||null:null,bedrooms:form.bedrooms?Number(form.bedrooms):null,bathrooms:form.bathrooms?Number(form.bathrooms):null,area_sqft:form.area_sqft?Number(form.area_sqft):null,plot_area_sqyd:form.plot_area_sqyd?Number(form.plot_area_sqyd):null,furnishing:form.furnishing||null,possession:form.possession||null,parking_spaces:form.parking_spaces?Number(form.parking_spaces):null,address_line:form.address_line.trim()||null,city:form.city.trim(),locality:form.locality.trim(),pincode:form.pincode.trim()||null,status};const inserted=await supabase.from("properties").insert(payload).select("id").single();if(inserted.error)throw inserted.error;await uploadImages(inserted.data.id,user.id);setMessage(status==="published"?"Your property is now live on UNLIVO.":"Draft saved successfully. You can return and publish it later.");setForm(initialForm);files.forEach(x=>URL.revokeObjectURL(x.url));setFiles([]);}catch(e:any){setError(e?.message||"We could not save the property. Please try again.");}finally{setSaving(false);}};

  return <main className="min-h-screen bg-[#f7fafb] text-[#102638]"><header className="border-b bg-white"><div className="container flex h-[78px] items-center justify-between"><a href="/" className="w-[180px] sm:w-[230px]"><img src="/unlivo-logo.svg" alt="UNLIVO" className="w-full"/></a><a href="/properties" className="inline-flex cursor-pointer items-center gap-2 text-sm font-bold"><ArrowLeft size={16}/> Browse properties</a></div></header><section className="container max-w-5xl py-10 lg:py-14"><div className="max-w-2xl"><p className="text-[11px] font-bold uppercase tracking-[3px] text-[#547083]">List with UNLIVO</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-1.5px]">Post a Property</h1><p className="mt-3 text-sm leading-6 text-[#687987]">Add your property once, keep control of your listing, and reach buyers and tenants searching on UNLIVO.</p></div>
  {!user?<div className="mt-8 rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm lg:p-8"><div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-[#e9faf6] text-[#0b8f79]"><LogIn size={20}/></div><div><h2 className="text-xl font-extrabold">{authMode==="signup"?"Create an account to list":"Sign in to list your property"}</h2><p className="mt-1 text-sm text-[#687987]">Your account keeps your listings, photos and future enquiries connected.</p></div></div><div className="mt-6 grid gap-4 md:grid-cols-2"><div><label className={labelClass}>Email</label><input className={inputClass} type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></div><div><label className={labelClass}>Password</label><input className={inputClass} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/></div></div><button onClick={authenticate} disabled={saving||!email||!password} className="mt-5 inline-flex cursor-pointer items-center justify-center rounded-xl bg-[#123b53] px-6 py-3 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">{saving?"Please wait…":authMode==="signup"?"Create account":"Sign in"}</button><button onClick={()=>{setAuthMode(authMode==="signup"?"login":"signup");setError("");setMessage("");}} className="ml-4 cursor-pointer text-sm font-bold text-[#087f73]">{authMode==="signup"?"Already have an account? Sign in":"Need an account? Sign up"}</button></div>:<form onSubmit={e=>{e.preventDefault();submit("published")}} className="mt-8 space-y-6">
    <div className="rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm lg:p-8"><h2 className="text-xl font-extrabold">1. Listing basics</h2><p className="mt-1 text-sm text-[#687987]">Tell buyers what you are offering.</p><div className="mt-6 grid gap-4 md:grid-cols-2"><div><label className={labelClass}>Purpose</label><div className="grid grid-cols-2 gap-2">{(["sale","rent"] as const).map(v=><button type="button" key={v} onClick={()=>set("purpose",v)} className={`cursor-pointer rounded-xl border px-4 py-3 text-sm font-bold ${form.purpose===v?"border-[#0bb89b] bg-[#e9faf6] text-[#087f73]":"border-[#d7e3e8]"}`}>{v==="sale"?"For Sale":"For Rent"}</button>)}</div></div><div><label className={labelClass}>Category</label><select className={inputClass} value={form.category} onChange={e=>set("category",e.target.value)}><option value="residential">Residential</option><option value="commercial">Commercial</option><option value="plot_land">Plots & Land</option><option value="project">Projects</option></select></div><div><label className={labelClass}>Property type</label><input className={inputClass} value={form.property_type} onChange={e=>set("property_type",e.target.value)} placeholder="Apartment, Villa, Office, Plot…"/></div><div><label className={labelClass}>{form.purpose==="sale"?"Sale price (₹)":"Monthly rent (₹)"}</label><input className={inputClass} type="number" min="0" value={form.purpose==="sale"?form.price:form.rent_monthly} onChange={e=>set(form.purpose==="sale"?"price":"rent_monthly",e.target.value)}/></div><div className="md:col-span-2"><label className={labelClass}>Listing title</label><input className={inputClass} value={form.title} onChange={e=>set("title",e.target.value)} placeholder="3 BHK Premium Apartment in Sector 88"/></div><div className="md:col-span-2"><label className={labelClass}>Description</label><textarea className={`${inputClass} min-h-32`} value={form.description} onChange={e=>set("description",e.target.value)} placeholder="Describe the property, condition, highlights and anything a buyer should know…"/></div></div></div>
    <div className="rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm lg:p-8"><h2 className="text-xl font-extrabold">2. Property details</h2><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{needsBedrooms&&<><div><label className={labelClass}>Bedrooms</label><input className={inputClass} type="number" min="0" value={form.bedrooms} onChange={e=>set("bedrooms",e.target.value)}/></div><div><label className={labelClass}>Bathrooms</label><input className={inputClass} type="number" min="0" value={form.bathrooms} onChange={e=>set("bathrooms",e.target.value)}/></div></>}{needsArea&&<div><label className={labelClass}>Area (sq ft)</label><input className={inputClass} type="number" min="0" value={form.area_sqft} onChange={e=>set("area_sqft",e.target.value)}/></div>}{form.category==="plot_land"&&<div><label className={labelClass}>Plot area (sq yd)</label><input className={inputClass} type="number" min="0" value={form.plot_area_sqyd} onChange={e=>set("plot_area_sqyd",e.target.value)}/></div>}<div><label className={labelClass}>Parking spaces</label><input className={inputClass} type="number" min="0" value={form.parking_spaces} onChange={e=>set("parking_spaces",e.target.value)}/></div><div><label className={labelClass}>Furnishing</label><select className={inputClass} value={form.furnishing} onChange={e=>set("furnishing",e.target.value)}><option value="">Select</option><option value="unfurnished">Unfurnished</option><option value="semi_furnished">Semi furnished</option><option value="fully_furnished">Fully furnished</option></select></div><div><label className={labelClass}>Possession</label><select className={inputClass} value={form.possession} onChange={e=>set("possession",e.target.value)}><option value="ready_to_move">Ready to move</option><option value="under_construction">Under construction</option><option value="pre_launch">Pre-launch</option><option value="resale">Resale</option></select></div></div></div>
    <div className="rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm lg:p-8"><h2 className="text-xl font-extrabold">3. Location</h2><div className="mt-6 grid gap-4 md:grid-cols-2"><div className="md:col-span-2"><label className={labelClass}>Address</label><input className={inputClass} value={form.address_line} onChange={e=>set("address_line",e.target.value)} placeholder="Sector / street / building address"/></div><div><label className={labelClass}>City</label><input className={inputClass} value={form.city} onChange={e=>set("city",e.target.value)} placeholder="Mohali"/></div><div><label className={labelClass}>Locality / Sector</label><input className={inputClass} value={form.locality} onChange={e=>set("locality",e.target.value)} placeholder="Sector 88"/></div><div><label className={labelClass}>Pincode</label><input className={inputClass} inputMode="numeric" value={form.pincode} onChange={e=>set("pincode",e.target.value)} placeholder="140301"/></div></div></div>
    <div className="rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm lg:p-8"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-extrabold">4. Property photos</h2><p className="mt-1 text-sm text-[#687987]">Upload up to 10 photos. The first photo becomes the cover image.</p></div><ImagePlus className="text-[#0bb89b]"/></div><label className="mt-6 flex cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-[#cbdde3] bg-[#f8fbfc] px-6 py-10 text-center transition hover:border-[#0bb89b] hover:bg-[#f1fbf9]"><Upload className="text-[#0bb89b]"/><span className="mt-3 text-sm font-bold">Choose property photos</span><span className="mt-1 text-xs text-[#687987]">Select multiple images at once</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple className="hidden" onChange={e=>chooseFiles(e.target.files)}/></label>{files.length>0&&<div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-5">{files.map((item,index)=><div key={`${item.file.name}-${item.file.lastModified}`} className="group relative overflow-hidden rounded-xl border border-[#dfe9ed] bg-white"><img src={item.url} alt={`Property photo ${index+1}`} className="aspect-square w-full object-cover"/>{index===0&&<span className="absolute left-2 top-2 rounded-full bg-white px-2 py-1 text-[9px] font-extrabold uppercase tracking-wide text-[#087f73]">Cover</span>}<button type="button" onClick={()=>removeFile(index)} aria-label={`Remove photo ${index+1}`} className="absolute right-2 top-2 cursor-pointer rounded-full bg-black/60 p-1.5 text-white"><X size={14}/></button></div>)}</div>}</div>
    {(message||error)&&<div className={`rounded-2xl p-4 text-sm ${error?"border border-[#f0d6d6] bg-[#fff7f7] text-[#8b4b4b]":"border border-[#ccebe4] bg-[#f1fbf8] text-[#087f73]"}`}>{!error&&<CheckCircle2 size={18} className="mr-2 inline"/>}{error||message}</div>}
    <div className="flex flex-col gap-3 border-t border-[#dfe9ed] pt-5 sm:flex-row sm:justify-end"><button type="button" onClick={()=>submit("draft")} disabled={saving} className="inline-flex cursor-pointer items-center justify-center rounded-xl border border-[#cbdde3] bg-white px-6 py-3.5 text-sm font-bold text-[#123b53] disabled:opacity-50">Save as Draft</button><button type="submit" disabled={saving} className="inline-flex cursor-pointer items-center justify-center rounded-xl bg-[#123b53] px-7 py-3.5 text-sm font-bold text-white transition hover:bg-[#102f44] disabled:cursor-not-allowed disabled:opacity-50">{saving?"Publishing…":"Publish Property"}</button></div>
  </form>}{(message||error)&&!user&&<div className={`mt-5 rounded-2xl p-4 text-sm ${error?"bg-[#fff7f7] text-[#8b4b4b]":"bg-[#f1fbf8] text-[#087f73]"}`}>{error||message}</div>}</section></main>;
}
