import { ArrowRight, BarChart3, CheckCircle2, ChevronDown, Heart, Handshake, Home, MapPin, ShieldCheck, Users } from "lucide-react";
import PropertySearch from "../components/property-search";

const properties = [
  { tag:"For Sale", title:"4 BHK Luxury Villa", location:"New Chandigarh, Punjab", price:"₹ 2.75 Cr", meta:["4 Beds","4 Baths","3,200 sq ft"], image:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=90" },
  { tag:"For Rent", title:"3 BHK Apartment", location:"Sector 66, Gurgaon", price:"₹ 65,000 /month", meta:["3 Beds","3 Baths","1,850 sq ft"], image:"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=90" },
  { tag:"Commercial", title:"Premium Office Space", location:"Cyber City, Gurgaon", price:"₹ 4.5 Cr", meta:["5,000 sq ft","Ready","Parking"], image:"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1000&q=90" },
  { tag:"Plot / Land", title:"Residential Plot", location:"New Chandigarh, Punjab", price:"₹ 1.2 Cr", meta:["300 sq yd","Gated","Road Facing"], image:"https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1000&q=90" },
];

const nav = ["Buy","Rent","Sell","For Brokers"];

export default function HomePage() {
  return <main>
    <header className="absolute left-0 right-0 top-0 z-30"><div className="container flex h-[82px] items-center justify-between"><a href="#" aria-label="UNLIVO home" className="block w-[180px] sm:w-[230px]"><img src="/unlivo-logo.svg" alt="UNLIVO" className="h-auto w-full" /></a><nav className="hidden items-center gap-9 md:flex">{nav.map(x=><a key={x} href={x === "For Brokers" ? "#brokers" : x === "Sell" ? "/post-property" : "#search"} className="cursor-pointer text-[13px] font-medium text-[#193246] transition hover:text-[#08aa91]">{x}</a>)}<a href="#resources" className="flex cursor-pointer items-center gap-1 text-[13px] font-medium text-[#193246] hover:text-[#08aa91]">Resources <ChevronDown size={15}/></a></nav><div className="flex items-center gap-3"><a href="/post-property" className="hidden cursor-pointer px-3 py-2 text-[13px] font-semibold text-[#193246] md:block">Login</a><a href="/post-property" className="cursor-pointer rounded-full bg-[#071d2d] px-6 py-3 text-[13px] font-bold text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-[#102f44]">Sign Up</a></div></div></header>
    <section className="hero-bg relative overflow-visible pt-24 sm:pt-28"><div className="container relative grid min-h-[600px] items-center gap-8 pb-[175px] lg:grid-cols-[.93fr_1.07fr] lg:pb-[150px]"><div className="relative z-10 pb-3 pt-8 lg:pt-0"><p className="mb-5 text-[10px] font-bold uppercase tracking-[3px] text-[#466274] sm:text-[11px]">A more connected real estate ecosystem</p><h1 className="max-w-[650px] text-[48px] font-extrabold leading-[.98] tracking-[-2.8px] text-[#102638] sm:text-[61px]">Find the right <span className="text-[#08b99e]">property.</span><br/>Find the right <span className="text-[#08b99e]">buyer.</span></h1><p className="mt-6 max-w-[535px] text-[15px] leading-7 text-[#536575] sm:text-[16px]">UNLIVO brings buyers, property owners and brokers together on one intelligent platform — making real estate simpler, faster and more transparent.</p><div className="mt-7 flex flex-wrap gap-3"><a href="#search" className="inline-flex cursor-pointer items-center gap-2 rounded-lg bg-[#071d2d] px-6 py-3.5 text-[13px] font-bold text-white shadow-lg transition hover:-translate-y-0.5">Explore Properties <ArrowRight size={17}/></a><a href="/post-property" className="inline-flex cursor-pointer items-center rounded-lg border border-[#9caeb9] bg-white/70 px-6 py-3.5 text-[13px] font-bold text-[#102638] transition hover:bg-white">Post a Property</a></div><div className="mt-9 grid max-w-[520px] grid-cols-3 gap-5"><Stat value="50K+" label="Properties Listed"/><Stat value="10K+" label="Trusted Brokers"/><Stat value="25K+" label="Happy Buyers"/></div></div><div className="relative hidden h-[500px] lg:block"><div className="hero-image absolute right-[-95px] top-[-5px] h-[520px] w-[760px] overflow-hidden rounded-bl-[155px] rounded-tl-[46px] shadow-2xl"><img src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=92" alt="Modern luxury home" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#e8f5f5]/10 via-transparent to-[#071d2d]/20"/></div><div className="glass absolute right-[-3px] top-16 w-[174px] rounded-xl p-6 text-white shadow-2xl sm:w-[184px]"><div className="text-[25px] font-light leading-8">More<br/>People<br/>More<br/>Possibilities</div><div className="mt-6 h-0.5 w-12 bg-[#21d0ae]"/><p className="mt-5 text-[9px] font-semibold uppercase tracking-[2px] leading-5 text-white/80">Property<br/>People<br/>Progress</p></div></div></div><div id="search" className="container absolute bottom-[-67px] left-1/2 z-20 w-[calc(100%-40px)] -translate-x-1/2"><PropertySearch /></div></section>
    <section className="container pt-[125px] pb-20 sm:pt-[135px]"><div className="grid gap-10 md:grid-cols-4"><Feature icon={<Home/>} title="Discover" text="Explore verified properties across cities"/><Feature icon={<Users/>} title="Connect" text="Get matched with the right buyers, sellers or brokers"/><Feature icon={<BarChart3/>} title="Make Better Decisions" text="Access insights, trends and market data"/><Feature icon={<Handshake/>} title="Build Brighter Futures" text="Be part of a more transparent and efficient real estate ecosystem"/></div></section>
    <section className="container pb-24"><div className="mb-8 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[3px] text-[#547083] sm:text-[11px]">Featured Properties</p><h2 className="mt-2 text-3xl font-extrabold tracking-[-1px] text-[#102638]">Handpicked for You</h2></div><a href="/properties" className="hidden cursor-pointer items-center gap-2 text-[13px] font-bold text-[#087f73] sm:flex">View All Properties <ArrowRight size={16}/></a></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{properties.map(p=><PropertyCard key={p.title} {...p}/>)}</div></section>
    <section id="brokers" className="bg-[#f1fbf9] py-20"><div className="container grid gap-10 lg:grid-cols-[1fr_1.1fr_.85fr] lg:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[3px] text-[#547083] sm:text-[11px]">Why UNLIVO</p><h2 className="mt-3 text-4xl font-extrabold leading-tight tracking-[-1.5px] text-[#102638]">Real Estate Works<br/>Better Together</h2><p className="mt-5 max-w-[450px] leading-7 text-[#5c6e7c]">We’re building a trusted, technology-driven platform that connects people, properties and opportunities across India.</p><a href="#" className="mt-7 inline-flex cursor-pointer items-center gap-2 rounded-lg bg-[#071d2d] px-6 py-3.5 text-[13px] font-bold text-white">Our Story <ArrowRight size={17}/></a></div><div className="space-y-5"><Benefit icon={<ShieldCheck/>} title="Verified Listings" text="Genuine properties, verified sources"/><Benefit icon={<CheckCircle2/>} title="Smart Matching" text="Connect with the right people faster"/><Benefit icon={<MapPin/>} title="Pan-India Reach" text="Opportunities across major cities"/><Benefit icon={<Users/>} title="Built for Brokers" text="Tools to grow your business"/></div><div className="relative min-h-[350px] overflow-hidden rounded-2xl"><img src="https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=90" alt="Modern city skyline" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-[#071d2d]/55"/><div className="relative p-8 text-white"><p className="max-w-[220px] text-2xl font-light uppercase tracking-[2px]">India’s Property Potential Unlocked</p><div className="mt-7 h-0.5 w-12 bg-[#2bd2b0]"/></div></div></div></section>
    <section id="requirement" className="bg-[#071d2d] py-16 text-white"><div className="container flex flex-col gap-8 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-3xl font-extrabold tracking-[-1px]">Be Part of a More Connected<br/>Real Estate Future</h2><p className="mt-3 max-w-[650px] text-sm leading-6 text-white/65">Whether you’re a buyer, owner or broker — UNLIVO gives you the tools, reach and support to achieve more.</p></div><a href="/post-property" className="inline-flex shrink-0 cursor-pointer items-center justify-center gap-2 rounded-lg bg-[#13c6a3] px-7 py-4 text-[13px] font-extrabold text-[#06251f]">Get Started <ArrowRight size={17}/></a></div></section>
    <footer id="resources" className="border-t border-[#e5ecef] py-10"><div className="container flex flex-col gap-4 text-sm text-[#667887] md:flex-row md:items-center md:justify-between"><a href="#" className="w-[160px]" aria-label="UNLIVO home"><img src="/unlivo-logo.svg" alt="UNLIVO" className="w-full"/></a><p>© 2026 UNLIVO. Find the right property. Find the right buyer.</p><div className="flex gap-5"><a href="#">Privacy</a><a href="#">Terms</a><a href="#">Contact</a></div></div></footer>
  </main>
}
function Stat({value,label}:{value:string,label:string}){return <div><div className="text-2xl font-extrabold tracking-[-.7px] text-[#102638]">{value}</div><div className="mt-1 text-[11px] text-[#687987]">{label}</div></div>}
function Feature({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div className="text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#e9faf6] text-[#0aa88e]">{icon}</div><h3 className="mt-4 font-extrabold text-[#102638]">{title}</h3><p className="mx-auto mt-2 max-w-[220px] text-sm leading-6 text-[#657684]">{text}</p></div>}
function PropertyCard({tag,title,location,price,meta,image}:{tag:string,title:string,location:string,price:string,meta:string[],image:string}){return <a href="/properties" className="card group block cursor-pointer transition hover:-translate-y-1 hover:shadow-lg"><div className="relative h-48"><img src={image} alt="" className="h-full w-full object-cover"/><span className="absolute left-3 top-3 rounded-full bg-white px-3 py-1 text-[11px] font-bold text-[#153246]">{tag}</span><span className="absolute right-3 top-3 rounded-full bg-black/25 p-2 text-white backdrop-blur"><Heart size={17}/></span></div><div className="p-4"><h3 className="font-extrabold text-[#102638]">{title}</h3><p className="mt-1 text-xs text-[#687987]">{location}</p><p className="mt-3 text-lg font-extrabold text-[#102638]">{price}</p><div className="mt-3 flex flex-wrap gap-x-3 gap-y-1 text-[11px] text-[#687987]">{meta.map(x=><span key={x}>{x}</span>)}</div></div></a>}
function Benefit({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div className="flex items-center gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-white text-[#0bb89b] shadow-sm">{icon}</div><div><h3 className="font-extrabold text-[#102638]">{title}</h3><p className="mt-1 text-sm text-[#657684]">{text}</p></div></div>}
