"use client";

import { useEffect, useState } from "react";
import { ArrowRight, BarChart3, CheckCircle2, ChevronDown, Heart, Handshake, Home, MapPin, ShieldCheck, Users } from "lucide-react";
import PropertySearch from "../components/property-search";
import SiteHeader from "../components/site-header";
import SiteFooter from "../components/site-footer";
import { supabase } from "../lib/supabase";

type Property={id:string;title:string;city:string;locality:string;price:number|null;rent_monthly:number|null;bedrooms:number|null;bathrooms:number|null;area_sqft:number|null;purpose:string;featured:boolean;cover?:string};
function price(p:Property){if(p.purpose==="rent")return p.rent_monthly==null?"Rent on request":`₹ ${p.rent_monthly.toLocaleString("en-IN")}/month`;if(p.price==null)return "Price on request";return p.price>=10000000?`₹ ${(p.price/10000000).toFixed(2)} Cr`:`₹ ${(p.price/100000).toFixed(2)} Lakh`}
export default function HomePage(){
 const [properties,setProperties]=useState<Property[]>([]);
 useEffect(()=>{async function load(){if(!supabase)return;const r=await supabase.from("properties").select("id,title,city,locality,price,rent_monthly,bedrooms,bathrooms,area_sqft,purpose,featured,property_media(storage_path,sort_order,is_cover)").eq("status","published").order("featured",{ascending:false}).order("created_at",{ascending:false}).limit(4);if(!r.error){const mapped=(r.data||[]).map((p:any)=>{const media=[...(p.property_media||[])].sort((a:any,b:any)=>(a.is_cover?0:1)-(b.is_cover?0:1)||a.sort_order-b.sort_order);const cover=media[0]?.storage_path?supabase!.storage.from("property-media").getPublicUrl(media[0].storage_path).data.publicUrl:undefined;return {...p,cover}});setProperties(mapped as Property[])}}load()},[]);
 return <main><SiteHeader overlay/><section className="hero-bg relative overflow-visible pt-24 sm:pt-28"><div className="container relative grid min-h-[600px] items-center gap-8 pb-[175px] lg:grid-cols-[.93fr_1.07fr] lg:pb-[150px]"><div className="relative z-10 pb-3 pt-8 lg:pt-0"><p className="mb-5 text-[10px] font-bold uppercase tracking-[3px] text-[#466274] sm:text-[11px]">A more connected real estate ecosystem</p><h1 className="max-w-[650px] text-[48px] font-extrabold leading-[.98] tracking-[-2.8px] text-[#102638] sm:text-[61px]">Find the right <span className="text-[#08b99e]">property.</span><br/>Find the right <span className="text-[#08b99e]">buyer.</span></h1><p className="mt-6 max-w-[535px] text-[15px] leading-7 text-[#536575] sm:text-[16px]">UNLIVO brings buyers, property owners and brokers together on one intelligent platform — making real estate simpler, faster and more transparent.</p><div className="mt-7 flex flex-wrap gap-3"><a href="#search" className="inline-flex cursor-pointer items-center gap-2 rounded-lg bg-[#071d2d] px-6 py-3.5 text-[13px] font-bold text-white shadow-lg">Explore Properties <ArrowRight size={17}/></a><a href="/post-property" className="inline-flex cursor-pointer items-center rounded-lg border border-[#9caeb9] bg-white/70 px-6 py-3.5 text-[13px] font-bold text-[#102638]">Post a Property</a></div><div className="mt-9 grid max-w-[520px] grid-cols-3 gap-5"><Stat value="Live" label="Published Listings"/><Stat value="Growing" label="Broker Network"/><Stat value="One Place" label="Property Journey"/></div></div><div className="relative hidden h-[500px] lg:block"><div className="hero-image absolute right-[-95px] top-[-5px] h-[520px] w-[760px] overflow-hidden rounded-bl-[155px] rounded-tl-[46px] shadow-2xl"><img src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=92" alt="Modern luxury home" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#e8f5f5]/10 via-transparent to-[#071d2d]/20"/></div><div className="glass absolute right-[-3px] top-16 w-[174px] rounded-xl p-6 text-white shadow-2xl sm:w-[184px]"><div className="text-[25px] font-light leading-8">More<br/>People<br/>More<br/>Possibilities</div><div className="mt-6 h-0.5 w-12 bg-[#21d0ae]"/><p className="mt-5 text-[9px] font-semibold uppercase tracking-[2px] leading-5 text-white/80">Property<br/>People<br/>Progress</p></div></div></div><div id="search" className="container absolute bottom-[-67px] left-1/2 z-20 w-[calc(100%-40px)] -translate-x-1/2"><PropertySearch /></div></section>
 <section className="container pt-[125px] pb-20 sm:pt-[135px]"><div className="grid gap-10 md:grid-cols-4"><Feature icon={<Home/>} title="Discover" text="Explore verified properties across cities"/><Feature icon={<Users/>} title="Connect" text="Get matched with the right buyers, sellers or brokers"/><Feature icon={<BarChart3/>} title="Make Better Decisions" text="Access insights, trends and market data"/><Feature icon={<Handshake/>} title="Build Brighter Futures" text="Be part of a more transparent and efficient real estate ecosystem"/></div></section>
 <section className="container pb-24"><div className="mb-8 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[3px] text-[#547083] sm:text-[11px]">Featured Properties</p><h2 className="mt-2 text-3xl font-extrabold tracking-[-1px] text-[#102638]">Latest on UNLIVO</h2></div><a href="/properties" className="hidden cursor-pointer items-center gap-2 text-[13px] font-bold text-[#087f73] sm:flex">View All Properties <ArrowRight size={16}/></a></div>{properties.length===0?<div className="rounded-3xl border border-[#dfe9ed] bg-white p-10 text-center text-sm text-[#687987]">New published UNLIVO listings will appear here automatically.</div>:<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{properties.map(p=><PropertyCard key={p.id} p={p}/>)}</div>}</section>
 <section id="brokers" className="bg-[#f1fbf9] py-20"><div className="container grid gap-10 lg:grid-cols-[1fr_1.1fr_.85fr] lg:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[3px] text-[#547083] sm:text-[11px]">Why UNLIVO</p><h2 className="mt-3 text-4xl font-extrabold leading-tight tracking-[-1.5px] text-[#102638]">Real Estate Works<br/>Better Together</h2><p className="mt-5 max-w-[450px] leading-7 text-[#5c6e7c]">We’re building a trusted, technology-driven platform that connects people, properties and opportunities across India.</p></div><div className="space-y-5"><Benefit icon={<ShieldCheck/>} title="Verified Listings" text="Genuine properties, verified sources"/><Benefit icon={<CheckCircle2/>} title="Smart Matching" text="Connect with the right people faster"/><Benefit icon={<MapPin/>} title="Location Intelligence" text="Search properties with better geographic context"/><Benefit icon={<Users/>} title="Built for Brokers" text="Tools to grow your business"/></div><div className="relative min-h-[350px] overflow-hidden rounded-2xl"><img src="https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=90" alt="Modern city skyline" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-[#071d2d]/55"/><div className="relative p-8 text-white"><p className="max-w-[220px] text-2xl font-light uppercase tracking-[2px]">India’s Property Potential Unlocked</p></div></div></div></section>
 <section className="bg-[#071d2d] py-16 text-white"><div className="container flex flex-col gap-8 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-3xl font-extrabold tracking-[-1px]">Be Part of a More Connected<br/>Real Estate Future</h2><p className="mt-3 max-w-[650px] text-sm leading-6 text-white/65">Whether you’re a buyer, owner or broker — UNLIVO gives you the tools, reach and support to achieve more.</p></div><a href="/post-property" className="inline-flex shrink-0 cursor-pointer items-center justify-center gap-2 rounded-lg bg-[#13c6a3] px-7 py-4 text-[13px] font-extrabold text-[#06251f]">Get Started <ArrowRight size={17}/></a></div></section><SiteFooter/></main>
}
function Stat({value,label}:{value:string,label:string}){return <div><div className="text-2xl font-extrabold tracking-[-.7px] text-[#102638]">{value}</div><div className="mt-1 text-[11px] text-[#687987]">{label}</div></div>}
function Feature({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div className="text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#e9faf6] text-[#0aa88e]">{icon}</div><h3 className="mt-4 font-extrabold text-[#102638]">{title}</h3><p className="mx-auto mt-2 max-w-[220px] text-sm leading-6 text-[#657684]">{text}</p></div>}
function PropertyCard({p}:{p:Property}){const meta=[p.bedrooms!=null?`${p.bedrooms} Beds`:null,p.bathrooms!=null?`${p.bathrooms} Baths`:null,p.area_sqft!=null?`${p.area_sqft.toLocaleString("en-IN")} sq ft`:null].filter(Boolean) as string[];return <a href={`/properties/${p.id}`} className="card group block cursor-pointer overflow-hidden transition hover:-translate-y-1 hover:shadow-lg"><div className="relative h-48 bg-[#e9faf6]">{p.cover?<img src={p.cover} alt={p.title} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-[#0bb89b]"><Home size={38}/></div>}<span className="absolute left-3 top-3 rounded-full bg-white px-3 py-1 text-[11px] font-bold text-[#153246]">{p.purpose==="rent"?"For Rent":"For Sale"}</span><span className="absolute right-3 top-3 rounded-full bg-black/25 p-2 text-white backdrop-blur"><Heart size={17}/></span></div><div className="p-4"><h3 className="font-extrabold text-[#102638]">{p.title}</h3><p className="mt-1 text-xs text-[#687987]">{p.locality}, {p.city}</p><p className="mt-3 text-lg font-extrabold text-[#102638]">{price(p)}</p><div className="mt-3 flex flex-wrap gap-x-3 gap-y-1 text-[11px] text-[#687987]">{meta.map(x=><span key={x}>{x}</span>)}</div></div></a>}
function Benefit({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div className="flex items-center gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-white text-[#0bb89b] shadow-sm">{icon}</div><div><h3 className="font-extrabold text-[#102638]">{title}</h3><p className="mt-1 text-sm text-[#657684]">{text}</p></div></div>}
