"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, LogOut, Mail, MapPin, Save, Phone, UserCircle } from "lucide-react";
import SiteHeader from "../../components/site-header";
import SiteFooter from "../../components/site-footer";
import { supabase } from "../../lib/supabase";
const input="w-full rounded-xl border border-[#d7e3e8] bg-white px-4 py-3 text-sm text-[#102638] outline-none focus:border-[#0bb89b] focus:ring-2 focus:ring-[#0bb89b]/10";
const label="mb-2 block text-xs font-bold uppercase tracking-[1.3px] text-[#547083]";
export default function ProfilePage(){
 const[user,setUser]=useState<any>(null);const[profile,setProfile]=useState<any>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");const[name,setName]=useState("");const[phone,setPhone]=useState("");const[city,setCity]=useState("");const[locality,setLocality]=useState("");const[email,setEmail]=useState("");const[otp,setOtp]=useState("");const[otpSent,setOtpSent]=useState(false);const[phoneVerified,setPhoneVerified]=useState(false);
 useEffect(()=>{async function load(){if(!supabase)return;const{data}=await supabase.auth.getUser();if(!data.user){window.location.href="/post-property?mode=login";return}setUser(data.user);setEmail(data.user.email||"");const p=await supabase.from("profiles").select("full_name,phone,city,locality,role,email,phone_verified").eq("id",data.user.id).maybeSingle();if(p.data){setProfile(p.data);setName(p.data.full_name||"");setPhone(p.data.phone||"");setCity(p.data.city||"");setLocality(p.data.locality||"");setPhoneVerified(Boolean(p.data.phone_verified))}setLoading(false)}load()},[]);
 const save=async()=>{if(!supabase||!user)return;setSaving(true);setError("");setMessage("");try{const r=await supabase.from("profiles").upsert({id:user.id,email:user.email||email,full_name:name.trim()||null,phone:phone.trim()||null,city:city.trim()||null,locality:locality.trim()||null,phone_verified:phoneVerified,updated_at:new Date().toISOString()},{onConflict:"id"});if(r.error)throw r.error;if(email.trim()&&email.trim().toLowerCase()!==(user.email||"").toLowerCase()){const er=await supabase.auth.updateUser({email:email.trim()});if(er.error)throw er.error;setMessage("Profile saved. A confirmation link has been sent to your new email address before the change becomes active.")}else setMessage("Profile updated successfully.")}catch(e:any){setError(e?.message||"We could not update your profile.")}finally{setSaving(false)}};
 const sendPhoneOtp=async()=>{if(!supabase||!phone.trim()){setError("Enter your phone number first.");return}setError("");setMessage("");const r=await supabase.auth.updateUser({phone:phone.trim()});if(r.error){setError(r.error.message);return}setOtpSent(true);setMessage("We sent a verification code to your phone.")};
 const verifyPhone=async()=>{if(!supabase||!otp.trim()){setError("Enter the verification code.");return}const r=await supabase.auth.verifyOtp({phone:phone.trim(),token:otp.trim(),type:"phone_change"});if(r.error){setError(r.error.message);return}setPhoneVerified(true);setOtpSent(false);setOtp("");setMessage("Phone number verified successfully.");await save()};
 const logout=async()=>{if(supabase)await supabase.auth.signOut();window.location.href="/"};
 if(loading)return <main className="min-h-screen bg-[#f7fafb] text-[#102638]"><SiteHeader/><div className="container py-24 text-center text-sm text-[#687987]">Loading your profile…</div><SiteFooter/></main>;
 return <main className="min-h-screen bg-[#f7fafb] text-[#102638]"><SiteHeader/><section className="container max-w-5xl py-12 lg:py-16"><p className="text-[11px] font-bold uppercase tracking-[3px] text-[#547083]">My UNLIVO</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-1px]">Profile & Contact Details</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#687987]">Keep your contact details current. Verified contact information will help UNLIVO connect you with genuine property enquiries.</p>{message&&<div className="mt-7 flex items-center gap-2 rounded-xl border border-[#bfe9df] bg-[#effbf8] px-4 py-3 text-sm font-semibold text-[#087f73]"><CheckCircle2 size={18}/>{message}</div>}{error&&<div className="mt-7 rounded-xl border border-[#efd0d0] bg-[#fff7f7] px-4 py-3 text-sm font-semibold text-[#8b4b4b]">{error}</div>}
 <div className="mt-8 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl border border-[#dfe9ed] bg-white p-7 shadow-sm lg:p-8"><div className="flex items-center gap-4 border-b border-[#e8eef1] pb-6"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-[#e9faf6] text-[#087f73]"><UserCircle size={30}/></div><div><h2 className="text-xl font-extrabold">Personal details</h2><p className="text-sm text-[#687987]">Account role: {profile?.role||"member"}</p></div></div><div className="mt-7 grid gap-5 md:grid-cols-2"><div><label className={label}>Full name</label><input className={input} value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name"/></div><div><label className={label}>City</label><input className={input} value={city} onChange={e=>setCity(e.target.value)} placeholder="Mohali"/></div><div><label className={label}>Locality</label><input className={input} value={locality} onChange={e=>setLocality(e.target.value)} placeholder="Sector 88"/></div><div><label className={label}>Email address</label><input className={input} type="email" value={email} onChange={e=>setEmail(e.target.value)}/><p className="mt-2 text-xs text-[#687987]">Changing your email requires confirmation at the new address.</p></div></div><div className="mt-5"><label className={label}>Phone number</label><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Phone className="absolute left-4 top-3.5 text-[#7b8c97]" size={17}/><input className={`${input} pl-11`} value={phone} onChange={e=>{setPhone(e.target.value);setPhoneVerified(false)}} placeholder="+91 98765 43210"/></div>{!phoneVerified&&!otpSent&&<button type="button" onClick={sendPhoneOtp} className="inline-flex h-12 shrink-0 cursor-pointer items-center justify-center rounded-xl bg-[#123b53] px-5 text-sm font-bold text-white">Verify by OTP</button>}{phoneVerified&&<span className="inline-flex h-12 shrink-0 items-center justify-center gap-2 rounded-xl bg-[#e9faf6] px-5 text-sm font-bold text-[#087f73]"><CheckCircle2 size={17}/> Verified</span>}</div>{otpSent&&<div className="mt-3 flex flex-col gap-3 sm:flex-row"><input className={`${input} sm:max-w-xs`} value={otp} onChange={e=>setOtp(e.target.value)} inputMode="numeric" placeholder="Enter OTP"/><button type="button" onClick={verifyPhone} className="inline-flex h-12 shrink-0 cursor-pointer items-center justify-center rounded-xl bg-[#0bb89b] px-5 text-sm font-extrabold text-white">Confirm OTP</button></div>}<p className="mt-2 text-xs text-[#687987]">Phone verification uses an OTP sent through Supabase Auth. SMS provider setup is required in Supabase.</p></div><button onClick={save} disabled={saving} className="mt-7 inline-flex h-12 cursor-pointer items-center justify-center gap-2 rounded-xl bg-[#0bb89b] px-6 text-sm font-extrabold text-white disabled:opacity-70"><Save size={17}/>{saving?"Saving…":"Save Changes"}</button></div>
 <div className="space-y-6"><div className="rounded-3xl border border-[#dfe9ed] bg-white p-7 shadow-sm"><h2 className="text-xl font-extrabold">Your account</h2><div className="mt-5 space-y-4 text-sm"><div className="flex gap-3"><Mail size={18} className="text-[#0bb89b]"/><div><p className="text-xs text-[#7b8c97]">Login email</p><p className="break-all font-semibold">{user?.email}</p></div></div><div className="flex gap-3"><Phone size={18} className="text-[#0bb89b]"/><div><p className="text-xs text-[#7b8c97]">Phone</p><p className="font-semibold">{phone||"Not added"} {phoneVerified&&<span className="text-[#087f73]">· Verified</span>}</p></div></div><div className="flex gap-3"><MapPin size={18} className="text-[#0bb89b]"/><div><p className="text-xs text-[#7b8c97]">Location</p><p className="font-semibold">{[locality,city].filter(Boolean).join(", ")||"Not added"}</p></div></div></div></div><div className="rounded-3xl border border-[#dfe9ed] bg-white p-7 shadow-sm"><h2 className="text-xl font-extrabold">Quick actions</h2><div className="mt-5 grid gap-3"><a href="/my-properties" className="rounded-xl bg-[#123b53] px-5 py-3 text-center text-sm font-bold text-white">My Properties</a><a href="/post-property" className="rounded-xl border border-[#d7e3e8] px-5 py-3 text-center text-sm font-bold">Post a Property</a><a href="/properties" className="rounded-xl border border-[#d7e3e8] px-5 py-3 text-center text-sm font-bold">Browse Properties</a><button onClick={logout} className="inline-flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-[#efd0d0] px-5 py-3 text-sm font-bold text-[#8b4b4b]"><LogOut size={17}/> Logout</button></div></div></div></div></section><SiteFooter/></main>;
}