"use client";

import { useEffect, useState } from "react";
import { LogOut, Mail, MapPin, Phone, UserCircle } from "lucide-react";
import SiteHeader from "../../components/site-header";
import SiteFooter from "../../components/site-footer";
import { supabase } from "../../lib/supabase";

export default function ProfilePage() {
  const [user,setUser]=useState<any>(null); const [profile,setProfile]=useState<any>(null); const [loading,setLoading]=useState(true);
  useEffect(()=>{async function load(){if(!supabase)return;const {data}=await supabase.auth.getUser();if(!data.user){window.location.href="/post-property?mode=login";return}setUser(data.user);const p=await supabase.from("profiles").select("full_name,phone,city,locality,role").eq("id",data.user.id).maybeSingle();setProfile(p.data);setLoading(false)}load()},[]);
  const logout=async()=>{if(supabase)await supabase.auth.signOut();window.location.href="/"};
  return <main className="min-h-screen bg-[#f7fafb] text-[#102638]"><SiteHeader/><section className="container max-w-4xl py-12 lg:py-16"><p className="text-[11px] font-bold uppercase tracking-[3px] text-[#547083]">My UNLIVO</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-1px]">Profile</h1>{loading?<p className="mt-6 text-sm text-[#687987]">Loading your profile…</p>:<div className="mt-8 grid gap-6 md:grid-cols-[1fr_.7fr]"><div className="rounded-3xl border border-[#dfe9ed] bg-white p-7 shadow-sm"><div className="flex items-center gap-4 border-b border-[#e8eef1] pb-6"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-[#e9faf6] text-[#087f73]"><UserCircle size={30}/></div><div><h2 className="text-xl font-extrabold">{profile?.full_name||"UNLIVO Member"}</h2><p className="text-sm text-[#687987]">{profile?.role||"buyer"}</p></div></div><div className="mt-6 space-y-5 text-sm"><div className="flex gap-3"><Mail size={18} className="text-[#0bb89b]"/><div><p className="text-xs text-[#7b8c97]">Email</p><p className="font-semibold">{user?.email}</p></div></div><div className="flex gap-3"><Phone size={18} className="text-[#0bb89b]"/><div><p className="text-xs text-[#7b8c97]">Phone</p><p className="font-semibold">{profile?.phone||"Not added yet"}</p></div></div><div className="flex gap-3"><MapPin size={18} className="text-[#0bb89b]"/><div><p className="text-xs text-[#7b8c97]">Location</p><p className="font-semibold">{[profile?.locality,profile?.city].filter(Boolean).join(", ")||"Not added yet"}</p></div></div></div></div><div className="rounded-3xl border border-[#dfe9ed] bg-white p-7 shadow-sm"><h2 className="text-xl font-extrabold">Quick actions</h2><div className="mt-5 grid gap-3"><a href="/post-property" className="rounded-xl bg-[#071d2d] px-5 py-3 text-center text-sm font-bold text-white">Post a Property</a><a href="/properties" className="rounded-xl border border-[#d7e3e8] px-5 py-3 text-center text-sm font-bold">Browse Properties</a><button onClick={logout} className="inline-flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-[#efd0d0] px-5 py-3 text-sm font-bold text-[#8b4b4b]"><LogOut size={17}/> Logout</button></div></div></div>}</section><SiteFooter/></main>;
}