"use client";

import { useEffect, useState } from "react";
import { ChevronDown, LogOut, Menu, UserCircle, X } from "lucide-react";
import { supabase } from "../lib/supabase";

export default function SiteHeader({ overlay = false }: { overlay?: boolean }) {
  const [user, setUser] = useState<any>(null); const [role,setRole]=useState(""); const [open,setOpen]=useState(false);
  useEffect(()=>{if(!supabase)return;const load=async()=>{const{data}=await supabase.auth.getUser();setUser(data.user);if(data.user){const p=await supabase.from("profiles").select("role").eq("id",data.user.id).maybeSingle();setRole(p.data?.role||"")}};load();const{data}=supabase.auth.onAuthStateChange((_e,s)=>{setUser(s?.user??null);if(!s?.user)setRole("")});return()=>data.subscription.unsubscribe()},[]);
  const logout=async()=>{if(supabase)await supabase.auth.signOut();window.location.href="/"};const nav=["Buy","Rent","Sell","For Brokers"];
  const accountLinks=<>{(role==="admin"||role==="reviewer")&&<a href="/admin/properties" className="rounded-lg px-3 py-3 text-sm font-semibold">Review Properties</a>}<a href="/my-properties" className="rounded-lg px-3 py-3 text-sm font-semibold">My Properties</a><a href="/profile" className="rounded-lg px-3 py-3 text-sm font-semibold">Profile</a><a href="/post-property" className="rounded-lg bg-[#071d2d] px-3 py-3 text-sm font-bold text-white">Post Property</a><button onClick={logout} className="flex cursor-pointer items-center gap-2 rounded-lg px-3 py-3 text-left text-sm font-semibold">Logout</button></>;
  return <header className={`${overlay?"absolute left-0 right-0 top-0 z-30":"border-b bg-white"}`}><div className="container flex h-[78px] items-center justify-between gap-5"><a href="/" aria-label="UNLIVO home" className="block w-[180px] shrink-0 sm:w-[230px]"><img src="/unlivo-logo.svg" alt="UNLIVO" className="h-auto w-full"/></a><nav className="hidden items-center gap-8 md:flex">{nav.map(x=><a key={x} href={x==="Sell"?"/post-property":"/properties"} className="cursor-pointer text-[13px] font-medium text-[#193246] transition hover:text-[#08aa91]">{x}</a>)}<a href="/#resources" className="flex cursor-pointer items-center gap-1 text-[13px] font-medium text-[#193246] hover:text-[#08aa91]">Resources <ChevronDown size={15}/></a></nav><div className="hidden items-center gap-3 md:flex">{user?<><a href="/my-properties" className="inline-flex cursor-pointer items-center rounded-full border border-[#d7e3e8] px-4 py-2.5 text-[13px] font-bold text-[#193246] hover:border-[#0bb89b]">My Properties</a><a href="/profile" className="inline-flex cursor-pointer items-center gap-2 rounded-full border border-[#d7e3e8] px-4 py-2.5 text-[13px] font-bold text-[#193246] hover:border-[#0bb89b]"><UserCircle size={17}/> Profile</a>{(role==="admin"||role==="reviewer")&&<a href="/admin/properties" className="cursor-pointer rounded-full border border-[#d7e3e8] px-4 py-2.5 text-[13px] font-bold text-[#193246] hover:border-[#0bb89b]">Review</a>}<a href="/post-property" className="cursor-pointer rounded-full bg-[#071d2d] px-5 py-2.5 text-[13px] font-bold text-white hover:bg-[#102f44]">Post Property</a><button onClick={logout} className="inline-flex cursor-pointer items-center gap-2 px-2 py-2 text-[13px] font-bold text-[#547083] hover:text-[#087f73]"><LogOut size={16}/> Logout</button></>:<><a href="/post-property?mode=login" className="cursor-pointer px-3 py-2 text-[13px] font-semibold text-[#193246]">Login</a><a href="/post-property" className="cursor-pointer rounded-full bg-[#071d2d] px-6 py-3 text-[13px] font-bold text-white shadow-lg hover:bg-[#102f44]">Sign Up</a></>}</div><button onClick={()=>setOpen(!open)} aria-label="Open menu" className="cursor-pointer rounded-xl p-2 md:hidden">{open?<X/>:<Menu/>}</button></div>{open&&<div className="border-t bg-white px-5 py-5 shadow-lg md:hidden"><div className="container grid gap-3">{nav.map(x=><a key={x} href={x==="Sell"?"/post-property":"/properties"} className="rounded-lg px-3 py-3 text-sm font-semibold">{x}</a>)}<a href="/#resources" className="rounded-lg px-3 py-3 text-sm font-semibold">Resources</a>{user?accountLinks:<><a href="/post-property?mode=login" className="rounded-lg px-3 py-3 text-sm font-semibold">Login</a><a href="/post-property" className="rounded-lg bg-[#071d2d] px-3 py-3 text-sm font-bold text-white">Sign Up</a></>}</div></div>}</header>;
}