"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, MailPlus, ShieldCheck, UserRound } from "lucide-react";
import SiteHeader from "../../../components/site-header";
import SiteFooter from "../../../components/site-footer";
import { supabase } from "../../../lib/supabase";

type Reviewer={id:string;full_name:string|null;email:string|null;role:string};

export default function AdminReviewersPage(){
 const[reviewers,setReviewers]=useState<Reviewer[]>([]);const[email,setEmail]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
 const load=async()=>{if(!supabase)return;setError("");const u=await supabase.auth.getUser();if(!u.data.user){setError("Please sign in to access reviewer management.");setLoading(false);return}const profile=await supabase.from("profiles").select("role").eq("id",u.data.user.id).maybeSingle();if(profile.error||profile.data?.role!=="admin"){setError("Admin access is required to manage reviewers.");setLoading(false);return}const r=await supabase.from("profiles").select("id,full_name,email,role").in("role",["reviewer","admin"]).order("full_name");if(r.error)setError(r.error.message);else setReviewers((r.data||[]) as Reviewer[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const invite=async()=>{if(!supabase||!email.trim())return;setSaving(true);setError("");setMessage("");const r=await supabase.functions.invoke("admin-invite-reviewer",{body:{email:email.trim().toLowerCase()}});if(r.error)setError(r.error.message);else{setMessage(r.data?.message||"Reviewer invitation sent.");setEmail("");await load()}setSaving(false)};
 if(loading)return <main className="min-h-screen bg-[#f7fafb] text-[#102638]"><SiteHeader/><div className="container py-24 text-center text-sm text-[#687987]">Loading reviewer management…</div><SiteFooter/></main>;
 return <main className="min-h-screen bg-[#f7fafb] text-[#102638]"><SiteHeader/><section className="container max-w-5xl py-10 lg:py-14"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[3px] text-[#547083]">UNLIVO Admin</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-1.5px]">Reviewer Management</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#687987]">Invite and manage the team members who review property submissions. Reviewer access is separate from the property review queue.</p></div><a href="/admin/properties" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl border border-[#cbdde3] bg-white px-5 py-3 text-sm font-bold text-[#123b53] shadow-sm hover:border-[#0bb89b] hover:text-[#087f73]"><ArrowLeft size={17}/>Back to Review Queue</a></div>{error&&<div className="mt-7 rounded-xl border border-[#efd0d0] bg-[#fff7f7] px-4 py-3 text-sm font-semibold text-[#8b4b4b]">{error}</div>}{message&&<div className="mt-7 rounded-xl border border-[#bfe9df] bg-[#effbf8] px-4 py-3 text-sm font-semibold text-[#087f73]">{message}</div>}
 <section className="mt-8 rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm lg:p-8"><p className="text-xs font-bold uppercase tracking-[1.4px] text-[#547083]">Add a reviewer</p><h2 className="mt-2 text-2xl font-extrabold">Invite a team member</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#687987]">Existing UNLIVO accounts can be promoted immediately. New users receive an invitation and are assigned the reviewer role after accepting.</p><div className="mt-6 flex w-full max-w-2xl flex-col gap-3 sm:flex-row"><input className="flex-1 rounded-xl border border-[#d7e3e8] bg-white px-4 py-3 text-sm outline-none focus:border-[#0bb89b]" value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="reviewer@example.com"/><button onClick={invite} disabled={saving||!email.trim()} className="inline-flex h-12 shrink-0 cursor-pointer items-center justify-center gap-2 rounded-xl bg-[#123b53] px-5 text-sm font-bold text-white disabled:opacity-50"><MailPlus size={17}/>{saving?'Sending…':'Add Reviewer'}</button></div></section>
 <section className="mt-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[1.4px] text-[#547083]">Team</p><h2 className="mt-1 text-2xl font-extrabold">Reviewers</h2></div><span className="rounded-full bg-[#e9faf6] px-3 py-1 text-xs font-extrabold text-[#087f73]">{reviewers.filter(r=>r.role==='reviewer').length} reviewers</span></div><div className="mt-5 grid gap-3 md:grid-cols-2">{reviewers.map(r=><div key={r.id} className="flex items-center justify-between rounded-2xl border border-[#dfe9ed] bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#e9faf6] text-[#087f73]"><UserRound size={19}/></div><div><p className="text-sm font-extrabold">{r.full_name||'UNLIVO Reviewer'}</p><p className="text-xs text-[#687987]">{r.email||'Email not synced'} · {r.role}</p></div></div><ShieldCheck size={18} className="text-[#0bb89b]"/></div>)}</div></section></section><SiteFooter/></main>
