"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, MailPlus, UserPlus } from "lucide-react";
import { supabase } from "../../../../lib/supabase";

const input="w-full rounded-xl border border-[#d7e3e8] bg-white px-4 py-3 text-sm text-[#102638] outline-none focus:border-[#0bb89b] focus:ring-4 focus:ring-[#0bb89b]/10";
const label="mb-2 block text-xs font-bold uppercase tracking-[1.3px] text-[#547083]";

export default function AddReviewerPage(){
 const[firstName,setFirstName]=useState("");const[lastName,setLastName]=useState("");const[email,setEmail]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
 useEffect(()=>{(async()=>{if(!supabase)return;const u=await supabase.auth.getUser();if(!u.data.user){window.location.href="/admin/login";return}const p=await supabase.from("profiles").select("role").eq("id",u.data.user.id).maybeSingle();if(p.data?.role!=="admin"){setError("Admin access is required to invite reviewers.");setLoading(false);return}setLoading(false)})()},[]);
 const invite=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;const first=firstName.trim();const last=lastName.trim();const mail=email.trim().toLowerCase();if(!first||!last||!mail){setError("Please enter the reviewer's first name, last name and email.");return}setSaving(true);setError("");setMessage("");try{const r=await supabase.functions.invoke("admin-invite-reviewer",{body:{email:mail,firstName:first,lastName:last}});if(r.error)throw r.error;if(r.data?.error)throw new Error(r.data.error);setMessage(r.data?.message||"Reviewer invitation sent.");setFirstName("");setLastName("");setEmail("")}catch(err:any){setError(err?.message||"We could not send the reviewer invitation.")}finally{setSaving(false)}};
 if(loading)return <section className="px-5 py-24 text-center text-sm text-[#687987]">Loading…</section>;
 return <section className="px-5 py-8 lg:px-9 lg:py-10"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[3px] text-[#087f73]">UNLIVO Admin</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-1.5px]">Add Reviewer</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#687987]">Invite a team member to review property submissions. They will receive an email, confirm their invitation, set a password and then sign in through the Reviewer Portal.</p></div><a href="/admin/reviewers" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl border border-[#cbdde3] bg-white px-5 py-3 text-sm font-bold text-[#123b53] shadow-sm hover:border-[#0bb89b] hover:text-[#087f73]"><ArrowLeft size={17}/>Back to Reviewers</a></div>{error&&<div className="mt-7 rounded-xl border border-[#efd0d0] bg-[#fff7f7] px-4 py-3 text-sm font-semibold text-[#8b4b4b]">{error}</div>}{message&&<div className="mt-7 rounded-xl border border-[#bfe9df] bg-[#effbf8] px-4 py-3 text-sm font-semibold text-[#087f73]">{message}</div>}
 <form onSubmit={invite} className="mt-8 max-w-3xl rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm lg:p-8"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-[#e9faf6] text-[#087f73]"><UserPlus size={21}/></div><div><h2 className="text-2xl font-extrabold">Reviewer details</h2><p className="mt-1 text-sm leading-6 text-[#687987]">The name entered here will be used in the Reviewer Portal and Admin reviewer list.</p></div></div><div className="mt-7 grid gap-5 md:grid-cols-2"><div><label className={label}>First Name</label><input className={input} value={firstName} onChange={e=>setFirstName(e.target.value)} autoComplete="given-name" placeholder="First name" required/></div><div><label className={label}>Last Name</label><input className={input} value={lastName} onChange={e=>setLastName(e.target.value)} autoComplete="family-name" placeholder="Last name" required/></div><div className="md:col-span-2"><label className={label}>Email Address</label><input className={input} type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" placeholder="reviewer@example.com" required/></div></div><div className="mt-6 rounded-2xl bg-[#f7fafb] p-5"><div className="flex items-start gap-3"><MailPlus size={19} className="mt-0.5 shrink-0 text-[#0b8f79]"/><div><p className="text-sm font-extrabold">Invitation flow</p><p className="mt-1 text-sm leading-6 text-[#687987]">The reviewer will receive a secure UNLIVO invitation. After opening it, they will confirm the invitation, choose and confirm their password, and then be directed to Reviewer Login.</p></div></div></div><button type="submit" disabled={saving} className="mt-6 inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-[#123b53] px-6 text-sm font-bold text-white shadow-sm hover:bg-[#102f44] disabled:cursor-not-allowed disabled:opacity-60"><MailPlus size={17}/>{saving?"Sending invitation…":"Send Reviewer Invitation"}</button></form></section>;
}
