"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, ChevronRight, Loader2 } from "lucide-react";
import { supabase } from "../../lib/supabase";

const cities=["Chandigarh","Mohali","Panchkula","Zirakpur","New Chandigarh","Kharar"];
const types=["Apartment","Builder Floor","Independent House","Villa","Plot","Office","Shop","Showroom","Warehouse","Other"];
const possession=["ready_to_move","under_construction","pre_launch","resale"];
const furnishing=["unfurnished","semi_furnished","fully_furnished"];

export default function PostRequirement(){
 const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[done,setDone]=useState(false);const[error,setError]=useState("");
 const[purpose,setPurpose]=useState("sale");const[category,setCategory]=useState("residential");const[propertyTypes,setPropertyTypes]=useState<string[]>(["Apartment"]);const[selectedCities,setSelectedCities]=useState<string[]>(["Mohali"]);const[localities,setLocalities]=useState("");const[minPrice,setMinPrice]=useState("");const[maxPrice,setMaxPrice]=useState("");const[minBeds,setMinBeds]=useState("");const[maxBeds,setMaxBeds]=useState("");const[minArea,setMinArea]=useState("");const[maxArea,setMaxArea]=useState("");const[possessionPrefs,setPossessionPrefs]=useState<string[]>([]);const[furnishingPrefs,setFurnishingPrefs]=useState<string[]>([]);const[notes,setNotes]=useState("");
 useEffect(()=>{(async()=>{if(!supabase)return;const u=await supabase.auth.getUser();if(!u.data.user){window.location.href="/login";return}const p=await supabase.from("profiles").select("role,access_status").eq("id",u.data.user.id).maybeSingle();if(p.data?.role==="admin"||p.data?.role==="reviewer"){setError("This workflow is for buyers. Please use the appropriate portal for your account.");}setLoading(false)})()},[]);
 const toggle=(value:string,list:string[],set:(v:string[])=>void)=>set(list.includes(value)?list.filter(x=>x!==value):[...list,value]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setError("");if(!selectedCities.length){setError("Please select at least one preferred city.");return}if(!propertyTypes.length){setError("Please select at least one property type.");return}if(maxPrice&&minPrice&&Number(maxPrice)<Number(minPrice)){setError("Maximum budget must be greater than minimum budget.");return}setSaving(true);const u=await supabase.auth.getUser();if(!u.data.user){window.location.href="/login";return}const r=await supabase.from("buyer_requirements").insert({user_id:u.data.user.id,purpose,category,property_types:propertyTypes,preferred_cities:selectedCities,preferred_localities:localities.split(",").map(x=>x.trim()).filter(Boolean),min_price:minPrice?Number(minPrice):null,max_price:maxPrice?Number(maxPrice):null,min_bedrooms:minBeds?Number(minBeds):null,max_bedrooms:maxBeds?Number(maxBeds):null,min_area_sqft:minArea?Number(minArea):null,max_area_sqft:maxArea?Number(maxArea):null,possession_preferences:possessionPrefs,furnishing_preferences:furnishingPrefs,amenities:[],notes:notes.trim()||null,status:"active"});if(r.error)setError(r.error.message);else setDone(true);setSaving(false)};
 const field="mt-1 w-full rounded-xl border border-[#d7e3e8] bg-white px-4 py-3 text-sm outline-none focus:border-[#0bb89b]";
 if(loading)return <main className="flex min-h-screen items-center justify-center bg-[#f5f8fa] text-sm text-[#687987]">Loading…</main>;
 if(done)return <main className="min-h-screen bg-[#f5f8fa] px-5 py-16"><div className="mx-auto max-w-2xl rounded-3xl border border-[#dfe9ed] bg-white p-10 text-center shadow-sm"><CheckCircle2 className="mx-auto text-[#0bb89b]" size={48}/><h1 className="mt-5 text-3xl font-extrabold text-[#102638]">Requirement posted</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-[#687987]">We’ll use your requirement to identify matching properties. You can review your active requirements and matches from your dashboard.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><a href="/my-requirements" className="rounded-xl bg-[#0bb89b] px-6 py-3 text-sm font-extrabold text-white">View My Requirements</a><a href="/properties" className="rounded-xl border border-[#cbdde3] px-6 py-3 text-sm font-bold text-[#123b53]">Browse Properties</a></div></div></main>;
 return <main className="min-h-screen bg-[#f5f8fa] text-[#102638]"><div className="mx-auto max-w-4xl px-5 py-8 lg:py-12"><a href="/" className="text-sm font-bold text-[#087f73]">← Back to UNLIVO</a><div className="mt-7"><p className="text-[11px] font-bold uppercase tracking-[3px] text-[#087f73]">Buyer Demand</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-1.5px]">Post a Requirement</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#687987]">Tell us exactly what you’re looking for. UNLIVO will use these details to surface relevant properties instead of making you search through hundreds of listings.</p></div>{error&&<div className="mt-6 rounded-xl border border-[#efd0d0] bg-[#fff7f7] px-4 py-3 text-sm font-semibold text-[#8b4b4b]">{error}</div>}
 <form onSubmit={submit} className="mt-8 space-y-6">
  <section className="rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold">What are you looking for?</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Purpose<select value={purpose} onChange={e=>setPurpose(e.target.value)} className={field}><option value="sale">Buy</option><option value="rent">Rent</option></select></label><label className="text-sm font-bold">Category<select value={category} onChange={e=>setCategory(e.target.value)} className={field}><option value="residential">Residential</option><option value="commercial">Commercial</option><option value="plot_land">Plots &amp; Land</option><option value="project">Projects</option></select></label></div><p className="mt-5 text-sm font-bold">Property type</p><div className="mt-2 flex flex-wrap gap-2">{types.map(v=><button key={v} type="button" onClick={()=>toggle(v,propertyTypes,setPropertyTypes)} className={`rounded-full border px-3 py-2 text-xs font-bold ${propertyTypes.includes(v)?"border-[#0bb89b] bg-[#e9faf4] text-[#087f73]":"border-[#d7e3e8] bg-white text-[#60737e]"}`}>{v}</button>)}</div></section>
  <section className="rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold">Preferred locations</h2><p className="mt-1 text-sm text-[#687987]">Select one or more cities. You can add localities separated by commas.</p><div className="mt-5 flex flex-wrap gap-2">{cities.map(v=><button key={v} type="button" onClick={()=>toggle(v,selectedCities,setSelectedCities)} className={`rounded-full border px-3 py-2 text-xs font-bold ${selectedCities.includes(v)?"border-[#0bb89b] bg-[#e9faf4] text-[#087f73]":"border-[#d7e3e8] bg-white text-[#60737e]"}`}>{v}</button>)}</div><label className="mt-5 block text-sm font-bold">Preferred localities<input value={localities} onChange={e=>setLocalities(e.target.value)} className={field} placeholder="e.g. Sector 67, Aerocity, Phase 7"/></label></section>
  <section className="rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold">Budget &amp; size</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Minimum budget (₹)<input type="number" min="0" value={minPrice} onChange={e=>setMinPrice(e.target.value)} className={field} placeholder="80,00,000"/></label><label className="text-sm font-bold">Maximum budget (₹)<input type="number" min="0" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)} className={field} placeholder="1,20,00,000"/></label><label className="text-sm font-bold">Minimum bedrooms<input type="number" min="0" max="20" value={minBeds} onChange={e=>setMinBeds(e.target.value)} className={field} placeholder="2"/></label><label className="text-sm font-bold">Maximum bedrooms<input type="number" min="0" max="20" value={maxBeds} onChange={e=>setMaxBeds(e.target.value)} className={field} placeholder="3"/></label><label className="text-sm font-bold">Minimum area (sq ft)<input type="number" min="0" value={minArea} onChange={e=>setMinArea(e.target.value)} className={field} placeholder="1200"/></label><label className="text-sm font-bold">Maximum area (sq ft)<input type="number" min="0" value={maxArea} onChange={e=>setMaxArea(e.target.value)} className={field} placeholder="1800"/></label></div></section>
  <section className="rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold">Preferences</h2><p className="mt-1 text-sm text-[#687987]">Optional — use these to improve your matches.</p><p className="mt-5 text-sm font-bold">Possession</p><div className="mt-2 flex flex-wrap gap-2">{possession.map(v=><button key={v} type="button" onClick={()=>toggle(v,possessionPrefs,setPossessionPrefs)} className={`rounded-full border px-3 py-2 text-xs font-bold ${possessionPrefs.includes(v)?"border-[#0bb89b] bg-[#e9faf4] text-[#087f73]":"border-[#d7e3e8] bg-white text-[#60737e]"}`}>{v.replaceAll("_"," ")}</button>)}</div><p className="mt-5 text-sm font-bold">Furnishing</p><div className="mt-2 flex flex-wrap gap-2">{furnishing.map(v=><button key={v} type="button" onClick={()=>toggle(v,furnishingPrefs,setFurnishingPrefs)} className={`rounded-full border px-3 py-2 text-xs font-bold ${furnishingPrefs.includes(v)?"border-[#0bb89b] bg-[#e9faf4] text-[#087f73]":"border-[#d7e3e8] bg-white text-[#60737e]"}`}>{v.replaceAll("_"," ")}</button>)}</div><label className="mt-5 block text-sm font-bold">Anything else we should know?<textarea value={notes} onChange={e=>setNotes(e.target.value)} className={`${field} min-h-28`} placeholder="Examples: prefer a park-facing apartment, need two parking spaces, close to schools…"/></label></section>
  <div className="flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-[#071d2d] px-7 py-3.5 text-sm font-extrabold text-white shadow-lg disabled:opacity-60">{saving?<><Loader2 size={17} className="animate-spin"/>Posting…</>:<>Post Requirement <ChevronRight size={17}/></>}</button></div>
 </form></div></main>;
}
