"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, ChevronRight, Loader2 } from "lucide-react";
import SiteHeader from "../../components/site-header";
import SiteFooter from "../../components/site-footer";
import { supabase } from "../../lib/supabase";

const cities=["Chandigarh","Mohali","Panchkula","Zirakpur","New Chandigarh","Kharar"];
const categoryTypes:Record<string,string[]>={residential:["Apartment","Builder Floor","Independent House","Villa"],commercial:["Office","Office Floor","Shop","Showroom","Warehouse","Commercial Building","Retail Space","Other"],plot_land:["Residential Plot","Commercial Plot","Agricultural Land","Industrial Land","Farm Land","Other Land"],project:["Apartment Project","Villa Project","Plotted Development","Commercial Project","Mixed Use Project","Other Project"]};
const budgetOptions:Record<string,[string,number|null,number|null][]>={residential:[["Under ₹50 Lakh",null,5000000],["₹50 Lakh – ₹1 Crore",5000000,10000000],["₹1 – ₹2 Crore",10000000,20000000],["₹2 – ₹5 Crore",20000000,50000000],["₹5 Crore+",50000000,null]],commercial:[["Under ₹1 Crore",null,10000000],["₹1 – ₹2 Crore",10000000,20000000],["₹2 – ₹5 Crore",20000000,50000000],["₹5 – ₹10 Crore",50000000,100000000],["₹10 Crore+",100000000,null]],plot_land:[["Under ₹50 Lakh",null,5000000],["₹50 Lakh – ₹1 Crore",5000000,10000000],["₹1 – ₹2 Crore",10000000,20000000],["₹2 – ₹5 Crore",20000000,50000000],["₹5 Crore+",50000000,null]],project:[["Under ₹1 Crore",null,10000000],["₹1 – ₹2 Crore",10000000,20000000],["₹2 – ₹5 Crore",20000000,50000000],["₹5 – ₹10 Crore",50000000,100000000],["₹10 Crore+",100000000,null]]};
const sizeOptions:Record<string,[string,number|null,number|null,string][]>={residential:[["Up to 1,000 sq ft",null,1000,"sq ft"],["1,000 – 1,500 sq ft",1000,1500,"sq ft"],["1,500 – 2,000 sq ft",1500,2000,"sq ft"],["2,000 – 3,000 sq ft",2000,3000,"sq ft"],["3,000+ sq ft",3000,null,"sq ft"]],commercial:[["Up to 1,000 sq ft",null,1000,"sq ft"],["1,000 – 2,500 sq ft",1000,2500,"sq ft"],["2,500 – 5,000 sq ft",2500,5000,"sq ft"],["5,000 – 10,000 sq ft",5000,10000,"sq ft"],["10,000+ sq ft",10000,null,"sq ft"]],plot_land:[["Up to 100 sq yd",null,100,"sq yd"],["100 – 200 sq yd",100,200,"sq yd"],["200 – 500 sq yd",200,500,"sq yd"],["500 – 1,000 sq yd",500,1000,"sq yd"],["1,000+ sq yd",1000,null,"sq yd"]],project:[["Up to 1,000 sq ft",null,1000,"sq ft"],["1,000 – 1,500 sq ft",1000,1500,"sq ft"],["1,500 – 2,000 sq ft",1500,2000,"sq ft"],["2,000 – 3,000 sq ft",2000,3000,"sq ft"],["3,000+ sq ft",3000,null,"sq ft"]]};
const preferenceOptions:Record<string,{label:string;values:string[]}[]|undefined>={residential:[{label:"Possession",values:["ready_to_move","under_construction","pre_launch","resale"]},{label:"Furnishing",values:["unfurnished","semi_furnished","fully_furnished"]}],commercial:[{label:"Possession",values:["ready_to_move","under_construction","pre_launch","resale"]},{label:"Furnishing",values:["unfurnished","semi_furnished","fully_furnished"]}],plot_land:[{label:"Listing status",values:["ready_to_move","resale","pre_launch"]}],project:[{label:"Project status",values:["ready_to_move","under_construction","pre_launch"]}]};
const sentence=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function PostRequirement(){
 const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[done,setDone]=useState(false);const[error,setError]=useState("");
 const[purpose,setPurpose]=useState("sale");const[category,setCategory]=useState("residential");const[propertyTypes,setPropertyTypes]=useState<string[]>(["Apartment"]);const[selectedCities,setSelectedCities]=useState<string[]>(["Mohali"]);const[localities,setLocalities]=useState("");const[minPrice,setMinPrice]=useState("");const[maxPrice,setMaxPrice]=useState("");const[minBeds,setMinBeds]=useState("");const[maxBeds,setMaxBeds]=useState("");const[minArea,setMinArea]=useState("");const[maxArea,setMaxArea]=useState("");const[possessionPrefs,setPossessionPrefs]=useState<string[]>([]);const[furnishingPrefs,setFurnishingPrefs]=useState<string[]>([]);const[notes,setNotes]=useState("");
 const types=categoryTypes[category]||categoryTypes.residential;const prefs=preferenceOptions[category]||[];const budgetPresets=budgetOptions[category]||budgetOptions.residential;const sizePresets=sizeOptions[category]||sizeOptions.residential;const sizeUnit=category==="plot_land"?"sq yd":"sq ft";
 useEffect(()=>{(async()=>{if(!supabase)return;const u=await supabase.auth.getUser();if(!u.data.user){window.location.href="/login";return}const p=await supabase.from("profiles").select("role,access_status").eq("id",u.data.user.id).maybeSingle();if(p.data?.role==="admin"||p.data?.role==="reviewer")setError("This workflow is for buyers. Please use the appropriate portal for your account.");setLoading(false)})()},[]);
 useEffect(()=>{setPropertyTypes([]);setMinPrice("");setMaxPrice("");setMinArea("");setMaxArea("");setMinBeds("");setMaxBeds("");setPossessionPrefs([]);setFurnishingPrefs([])},[category]);
 const toggle=(value:string,list:string[],set:(v:string[])=>void)=>set(list.includes(value)?list.filter(x=>x!==value):[...list,value]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setError("");if(!selectedCities.length){setError("Please select at least one preferred city.");return}if(!propertyTypes.length){setError("Please select at least one property type.");return}if(maxPrice&&minPrice&&Number(maxPrice)<Number(minPrice)){setError("Maximum budget must be greater than minimum budget.");return}if(maxArea&&minArea&&Number(maxArea)<Number(minArea)){setError(`Maximum size must be greater than minimum size.`);return}setSaving(true);const u=await supabase.auth.getUser();if(!u.data.user){window.location.href="/login";return}const r=await supabase.from("buyer_requirements").insert({user_id:u.data.user.id,purpose,category,property_types:propertyTypes,preferred_cities:selectedCities,preferred_localities:localities.split(",").map(x=>x.trim()).filter(Boolean),min_price:minPrice?Number(minPrice):null,max_price:maxPrice?Number(maxPrice):null,min_bedrooms:minBeds?Number(minBeds):null,max_bedrooms:maxBeds?Number(maxBeds):null,min_area_sqft:minArea?Number(minArea):null,max_area_sqft:maxArea?Number(maxArea):null,possession_preferences:possessionPrefs,furnishing_preferences:furnishingPrefs,amenities:[],notes:notes.trim()||null,status:"active"});if(r.error)setError(r.error.message);else setDone(true);setSaving(false)};
 const field="mt-1 w-full rounded-xl border border-[#d7e3e8] bg-white px-4 py-3 text-sm outline-none focus:border-[#0bb89b]";
 const preset=(label:string,min:number|null,max:number|null,setMin:(v:string)=>void,setMax:(v:string)=>void)=>{setMin(min==null?"":String(min));setMax(max==null?"":String(max));};
 if(loading)return <main className="flex min-h-screen items-center justify-center bg-[#f5f8fa] text-sm text-[#687987]">Loading…</main>;
 if(done)return <><SiteHeader/><main className="min-h-[65vh] bg-[#f5f8fa] px-5 py-16"><div className="mx-auto max-w-2xl rounded-3xl border border-[#dfe9ed] bg-white p-10 text-center shadow-sm"><CheckCircle2 className="mx-auto text-[#0bb89b]" size={48}/><h1 className="mt-5 text-3xl font-extrabold text-[#102638]">Requirement posted</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-[#687987]">We’ll use your requirement to identify matching properties. You can review your active requirements and matches from your dashboard.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><a href="/my-requirements" className="rounded-xl bg-[#0bb89b] px-6 py-3 text-sm font-extrabold text-white">View My Requirements</a><a href="/properties" className="rounded-xl border border-[#cbdde3] px-6 py-3 text-sm font-bold text-[#123b53]">Browse Properties</a></div></div></main><SiteFooter/></>;
 return <><SiteHeader/><main className="min-h-screen bg-[#f5f8fa] text-[#102638]"><div className="mx-auto max-w-4xl px-5 py-8 lg:py-12"><div className="mt-1"><p className="text-[11px] font-bold uppercase tracking-[3px] text-[#087f73]">Buyer Demand</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-1.5px]">Post a Requirement</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#687987]">Tell us exactly what you’re looking for. UNLIVO will use these details to surface relevant properties instead of making you search through hundreds of listings.</p></div>{error&&<div className="mt-6 rounded-xl border border-[#efd0d0] bg-[#fff7f7] px-4 py-3 text-sm font-semibold text-[#8b4b4b]">{error}</div>}
 <form onSubmit={submit} className="mt-8 space-y-6">
  <section className="rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold">What are you looking for?</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Purpose<select value={purpose} onChange={e=>setPurpose(e.target.value)} className={field}><option value="sale">Buy</option><option value="rent">Rent</option></select></label><label className="text-sm font-bold">Category<select value={category} onChange={e=>setCategory(e.target.value)} className={field}><option value="residential">Residential</option><option value="commercial">Commercial</option><option value="plot_land">Plots &amp; Land</option><option value="project">Projects</option></select></label></div><p className="mt-5 text-sm font-bold">Property type</p><div className="mt-2 flex flex-wrap gap-2">{types.map(v=><button key={v} type="button" onClick={()=>toggle(v,propertyTypes,setPropertyTypes)} className={`rounded-full border px-3 py-2 text-xs font-bold ${propertyTypes.includes(v)?"border-[#0bb89b] bg-[#e9faf4] text-[#087f73]":"border-[#d7e3e8] bg-white text-[#60737e]"}`}>{v}</button>)}</div></section>
  <section className="rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold">Preferred locations</h2><p className="mt-1 text-sm text-[#687987]">Select one or more cities. You can add localities separated by commas.</p><div className="mt-5 flex flex-wrap gap-2">{cities.map(v=><button key={v} type="button" onClick={()=>toggle(v,selectedCities,setSelectedCities)} className={`rounded-full border px-3 py-2 text-xs font-bold ${selectedCities.includes(v)?"border-[#0bb89b] bg-[#e9faf4] text-[#087f73]":"border-[#d7e3e8] bg-white text-[#60737e]"}`}>{v}</button>)}</div><label className="mt-5 block text-sm font-bold">Preferred localities<input value={localities} onChange={e=>setLocalities(e.target.value)} className={field} placeholder="e.g. Sector 67, Aerocity, Phase 7"/></label></section>
  <section className="rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold">Budget &amp; size</h2><p className="mt-1 text-sm text-[#687987]">Choose a range or enter your own values.</p><p className="mt-5 text-sm font-bold">Budget</p><div className="mt-2 flex flex-wrap gap-2">{budgetPresets.map(([label,min,max])=><button key={label} type="button" onClick={()=>preset(label,min,max,setMinPrice,setMaxPrice)} className={`rounded-full border px-3 py-2 text-xs font-bold ${String(min??"")===minPrice&&String(max??"")===maxPrice?"border-[#0bb89b] bg-[#e9faf4] text-[#087f73]":"border-[#d7e3e8] bg-white text-[#60737e]"}`}>{label}</button>)}</div><div className="mt-4 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Minimum budget (₹)<input type="number" min="0" value={minPrice} onChange={e=>setMinPrice(e.target.value)} className={field} placeholder="Enter minimum"/></label><label className="text-sm font-bold">Maximum budget (₹)<input type="number" min="0" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)} className={field} placeholder="Enter maximum"/></label></div><p className="mt-6 text-sm font-bold">Size <span className="font-normal text-[#81929b]">({sizeUnit})</span></p><div className="mt-2 flex flex-wrap gap-2">{sizePresets.map(([label,min,max])=><button key={label} type="button" onClick={()=>preset(label,min,max,setMinArea,setMaxArea)} className={`rounded-full border px-3 py-2 text-xs font-bold ${String(min??"")===minArea&&String(max??"")===maxArea?"border-[#0bb89b] bg-[#e9faf4] text-[#087f73]":"border-[#d7e3e8] bg-white text-[#60737e]"}`}>{label}</button>)}</div><div className="mt-4 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Minimum size ({sizeUnit})<input type="number" min="0" value={minArea} onChange={e=>setMinArea(e.target.value)} className={field} placeholder="Enter minimum"/></label><label className="text-sm font-bold">Maximum size ({sizeUnit})<input type="number" min="0" value={maxArea} onChange={e=>setMaxArea(e.target.value)} className={field} placeholder="Enter maximum"/></label></div>{category==="residential"&&<div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Minimum bedrooms<input type="number" min="0" max="20" value={minBeds} onChange={e=>setMinBeds(e.target.value)} className={field} placeholder="e.g. 2"/></label><label className="text-sm font-bold">Maximum bedrooms<input type="number" min="0" max="20" value={maxBeds} onChange={e=>setMaxBeds(e.target.value)} className={field} placeholder="e.g. 3"/></label></div>}</section>
  <section className="rounded-3xl border border-[#dfe9ed] bg-white p-6 shadow-sm"><h2 className="text-xl font-extrabold">Preferences</h2><p className="mt-1 text-sm text-[#687987]">Optional — these filters are tailored to your selected property category.</p>{prefs.map(group=><div key={group.label} className="mt-5"><p className="text-sm font-bold">{group.label}</p><div className="mt-2 flex flex-wrap gap-2">{group.values.map(v=>{const active=(group.label==="Furnishing"?furnishingPrefs:possessionPrefs).includes(v);const setter=group.label==="Furnishing"?setFurnishingPrefs:setPossessionPrefs;return <button key={v} type="button" onClick={()=>toggle(v,group.label==="Furnishing"?furnishingPrefs:possessionPrefs,setter)} className={`rounded-full border px-3 py-2 text-xs font-bold ${active?"border-[#0bb89b] bg-[#e9faf4] text-[#087f73]":"border-[#d7e3e8] bg-white text-[#60737e]"}`}>{sentence(v)}</button>})}</div></div>)}<label className="mt-5 block text-sm font-bold">Anything else we should know?<textarea value={notes} onChange={e=>setNotes(e.target.value)} className={`${field} min-h-28`} placeholder="Examples: prefer a park-facing property, need parking, close to schools or public transport…"/></label></section>
  <div className="flex justify-end"><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-[#071d2d] px-7 py-3.5 text-sm font-extrabold text-white shadow-lg disabled:opacity-60">{saving?<><Loader2 size={17} className="animate-spin"/>Posting…</>:<>Post Requirement <ChevronRight size={17}/></>}</button></div>
 </form></div></main><SiteFooter/></>;
}
